name: todo_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/Icon.png
    - assets/icons/google.png
    - assets/icons/message.png
  fonts:
    - family: "AntipastoPro"
      fonts:
        - asset: assets/fonts/AntipastoPro-DemiBold_trial.ttf
    - family: "FredokaOne"
      fonts:
        - asset: assets/fonts/FredokaOne-Regular.ttf
